global:
  container:
    image:
      repository: cookielab/deployer
      tag: 1.0.0-rc2
  rollingUpdate:
    maxUnavailable: 50%
    maxSurge: 50%

components:
  api:
    type: http
    replicas: 2
    ports:
      - port: 3000
    probes:
      readinessProbe:
        httpGet:
          port: 8080
          path: /health-check
        periodSeconds: 30
        timeoutSeconds: 15
      livenessProbe:
        httpGet:
          port: 8080
          path: /health-check
    targetGroup:
      arn: 'arn:fake'
      securityGroupIds:
        - sg-fake
  consumer-foo:
    type: consumer
    command:
      - bin/cosume
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 30%
