{{- if .Values.externalSecrets }}
{{- range $externalSecretName, $externalSecret := .Values.externalSecrets }}
{{- if or (not (hasKey $externalSecret "enabled")) $externalSecret.enabled }}
{{- $externalSecretSpec := required (printf "externalSecrets.%s.spec is required when enabled" $externalSecretName) $externalSecret.spec }}
{{- $kind := tpl (($externalSecret.kind | default "VaultStaticSecret") | toString) $ }}
---
apiVersion: {{ tpl (($externalSecret.apiVersion | default (ternary "secrets.hashicorp.com/v1beta1" "external-secrets.io/v1" (eq $kind "VaultStaticSecret"))) | toString) $ }}
kind: {{ $kind }}
metadata:
  name: {{ tpl (($externalSecret.name | default $externalSecretName) | toString) $ | quote }}
  namespace: {{ tpl (($externalSecret.namespace | default $.Release.Namespace) | toString) $ | quote }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/component: external-secret
    {{- with $externalSecret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ toYaml $externalSecretSpec | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
