{{- range $componentName, $component := .Values.components -}}
{{- if and (eq $component.type "consumer") (not (empty $component.keda)) (eq $component.keda.type "kafka") -}}

{{- /* validate missing variables */ -}}
{{- if or (not $component.keda.kafka.consumerGroup) (not $component.keda.kafka.bootstrapServers) -}}
{{- fail (printf "KEDA Kafka consumer '%s': missing required environment variable(s). Please define 'consumerGroup' and 'bootstrapServers' in values.yaml" $componentName) -}}
{{- end -}}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "component.name" (dict "name" $componentName "Release" $.Release) }}-kafka
spec:
  cooldownPeriod: {{ $component.keda.cooldownPeriod | default 30 }}
  minReplicaCount: {{ if not (kindIs "invalid" $component.keda.minReplicaCount) }}{{ $component.keda.minReplicaCount }}{{ else }}{{ 0 }}{{ end }}
  maxReplicaCount: {{ $component.keda.maxReplicaCount | default 2 }}
  pollingInterval: {{ $component.keda.pollingInterval | default 15 }}
  scaleTargetRef:
    name: {{ include "component.name" (dict "name" $componentName "Release" $.Release) }}
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: {{ $component.keda.kafka.bootstrapServers | quote }}
      {{ if hasKey $component.keda.kafka "topic" -}}
      topic: {{ $component.keda.kafka.topic | quote }}
      {{ end -}}
      consumerGroup: {{ $component.keda.kafka.consumerGroup | quote }}
      activationLagThreshold: {{ $component.keda.kafka.activationLagThreshold | default "1" | quote }}
      lagThreshold: {{ $component.keda.kafka.lagThreshold | default "10" | quote }}
      tls: {{ $component.keda.kafka.tls | default "enable" | quote }}
      identityOwner: {{ $component.keda.kafka.identityOwner | default "operator"  }}
      {{ if (eq ($component.keda.kafka.identityOwner | default "operator") "operator") -}}
      awsRegion: {{ $component.keda.kafka.awsRegion | default $.Values.global.keda.awsRegion | quote }}
      sasl: oauthbearer
      saslTokenProvider: aws_msk_iam
      {{- end }}
{{ end -}}
{{- end -}}
