{{- range $componentName, $component := .Values.components -}}
{{- if and (ne $component.type "cronjob") (ne $component.type "pre-job") -}}
{{- $kubeLabels := (merge (dict "name" $.Release.Name "instance" (printf "%s-%d" (include "component.name" (dict "name" $componentName "Release" $.Release)) $.Release.Revision) "component" $componentName) $.Values.global.metadata) -}}
{{- if and $component.serviceAccountCreate $component.serviceAccountName }}
--
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $component.serviceAccountName }}
  labels:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/resource-policy: keep
{{- end }}
{{- end }}
{{- end }}

{{- if and .Values.global.serviceAccountCreate -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccountName }}
  labels:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/resource-policy: keep
{{- end }}

