{{- range $componentName, $component := .Values.components -}}
{{- if or (eq $component.type "http") (eq $component.type "http-internal") -}}
{{- $kubeLabels := (merge (dict "name" $.Release.Name "instance" (printf "%s-%d" (include "component.name" (dict "name" $componentName "Release" $.Release)) $.Release.Revision) "component" $componentName) $.Values.global.metadata) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "component.name" (dict "name" $componentName "Release" $.Release) }}
  labels:
    {{ include "cookielab.kubernetes.labels" $kubeLabels | indent 4 | trim }}
    {{ include "cookielab.kubernetes.labels.selector" $kubeLabels | indent 4 | trim }}
spec:
  type: {{ dig "service" "type" $.Values.global.service.type $component }}
  ports:
    {{- range $port := $component.ports }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
    {{- end }}
  selector:
    {{ include "cookielab.kubernetes.labels.selector" $kubeLabels | indent 4 | trim }}
{{ end -}}
{{- end -}}
