### In 1.33 should be released InPlacePodVerticalScaling
{{- range $componentName, $component := .Values.components -}}
{{- if and (ne $component.type "cronjob") (ne $component.type "pre-job") (and $component.vpa $component.vpa.enabled) -}}
{{- $kubeLabels := (merge (dict "name" $.Release.Name "instance" (printf "%s-%d" (include "component.name" (dict "name" $componentName "Release" $.Release)) $.Release.Revision) "component" $componentName) $.Values.global.metadata) -}}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "component.name" (dict "name" $componentName "Release" $.Release) }}
  labels:
    {{ include "cookielab.kubernetes.labels" $kubeLabels | indent 4 | trim }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       "Deployment"
    name:       {{ include "component.name" (dict "name" $componentName "Release" $.Release) }}
  updatePolicy:
    updateMode: {{ default "Auto" (default dict $component.vpa).updateMode | quote }}
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: {{ default "50m" (default dict $component.vpa).minCpu | quote }}
          memory: {{ default "128Mi" (default dict $component.vpa).minMemory | quote }}
        maxAllowed:
          cpu: {{ default "500m" (default dict $component.vpa).maxCpu | quote }}
          memory: {{ default "1Gi" (default dict $component.vpa).maxMemory | quote }}
        controlledResources: ["cpu", "memory"]
    {{- end }}
{{- end }}
