global:
  # metadata:
  #   partOf: project
  container:
    image:
      repository: cookielab/deployer
      tag: 1.0.0-rc2

components:
  cleanup:
    type: post-delete-job
    hooks:
      - post-delete
    command:
      - bin/cleanup
    envs:
      values:
        EXTERNAL_API_URL: "https://example.com"

  cleanup-without-command:
    type: post-delete-job
    hooks:
      - post-delete
    envs:
      values:
        EXTERNAL_API_URL: "https://example.com"
