global:
  container:
    image:
      repository: cookielab/deployer
      tag: 1.0.0-rc2

components:
  migrations:
    type: pre-job
    command:
      - bin/migrations
    envs:
      values:
        DATABASE_URL: '$(MIGRATOR_DATABASE_URL)'
