global:
  container:
    image:
      repository: cookielab/deployer
      tag: 1.0.0-rc2
    envs:
      from:
        secrets:
          - name: app-admin-vault-envs
            optional: true

externalSecrets:
  app-admin-vault-envs:
    spec:
      dataFrom:
        - extract:
            conversionStrategy: Default
            decodingStrategy: None
            key: dev/admin/envs
            metadataPolicy: None
      refreshInterval: 60s
      secretStoreRef:
        kind: SecretStore
        name: vault-secret-store
      target:
        creationPolicy: Owner
        deletionPolicy: Retain
        name: app-admin-vault-envs
        template:
          engineVersion: v2
          mergePolicy: Replace
          metadata:
            annotations:
              managed: ExternalSecretsOperator

components:
  api:
    type: http
    replicas: 2
    ports:
      - port: 3000
    probes:
      readinessProbe:
        httpGet:
          port: 8080
          path: /health-check
      livenessProbe:
        httpGet:
          port: 8080
          path: /health-check
    targetGroup:
      arn: "arn:fake"
      securityGroupIds:
        - sg-fake
