global:
  metadata:
    annotations:
      secrets.infisical.com/auto-reload: "true"
  container:
    image:
      repository: cookielab/deployer
      tag: 1.0.0-rc2
    envs:
      from:
        secrets:
          - name: app-infisical-envs
            optional: true

externalSecrets:
  app-infisical-envs:
    kind: InfisicalSecret
    spec:
      syncConfig:
        resyncInterval: 60s
      authentication:
        kubernetesAuth:
          identityId: 00000000-0000-0000-0000-000000000000
          autoCreateServiceAccountToken: true
          serviceAccountRef:
            name: app-infisical
            namespace: dev
          secretsScope:
            projectSlug: app-slug
            envSlug: dev
            secretsPath: /
      managedKubeSecretReferences:
        - secretName: app-infisical-envs
          secretNamespace: dev
          creationPolicy: Owner

components:
  api:
    type: http
    replicas: 2
    ports:
      - port: 3000
    probes:
      readinessProbe:
        httpGet:
          port: 8080
          path: /health-check
      livenessProbe:
        httpGet:
          port: 8080
          path: /health-check
    targetGroup:
      arn: "arn:fake"
      securityGroupIds:
        - sg-fake
