global:
  container:
    image:
      repository: cookielab/deployer
      tag: 1.0.0-rc2

components:
  api:
    type: http
    replicas: 2
    hpa:
      enabled: true
      maxReplicas: 10
    ports:
      - port: 3000
    probes:
      readinessProbe:
        httpGet:
          port: 8080
          path: /health-check
        periodSeconds: 30
        timeoutSeconds: 15
      livenessProbe:
        httpGet:
          port: 8080
          path: /health-check
    targetGroup:
      arn: "arn:fake"
      securityGroupIds:
        - sg-fake

  api-i1:
    type: consumer
    replicas: 1
    command:
      - bin/consume
    hpa:
      enabled: true
      maxReplicas: 3
      scaleUp:
        stabilizationWindowSeconds: 300
      scaleDown:
        stabilizationWindowSeconds: 600
